@startuml

!theme monokai_npp from ..\.styles
scale 1.3


abstract list

abstract OrganizationLevel {
    +title: <i>str</i>
    +description: <i>str</i>
    +head: Administrator
    #staff: <i>list</i> [Administrator]
    +contact: Contact
    ..<font size=12><i> getters  </i></font>..
    +staff() → <i>list</i> [Administrator]
}

class Contact << dataclass >> {
    +mobile: <i>str</i>
    +office: <i>str</i>
    +email: <i>str</i>
    +web: <i>str</i>
    +telegram: <i>str</i>
}


class University << singleton >> {
    <font size=12><font "Space Mono">Faculty</font>
    ..
    +hr: HR
    --
    +change_head() → <i>None</i>
}

class HR << singleton >> {
    +hire() → <i>None</i>
    +fire() → <i>None</i>
}

class Faculty {
    <font size=12><font "Space Mono">Department</font>
    --
    +enroll_student() → <i>None</i>
    +expel_student() → <i>None</i>
}

class Department {
    <font size=12><font "Space Mono">Group</font>
    ..
    +teachers: <i>list</i> [Teacher]
    +auditoria: <i>list</i> [Auditorium]
}

class Auditorium << dataclass >> {
    +number: <i>str</i>
    +seats: <i>int</i>
    +building: <i>str</i>
}

class Group {
    <font size=12><font "Space Mono">Student</font>
    ..
    +id: <i>str</i>
    +chief: Student
    +curator Teacher
}


hide abstract empty members
hide enum empty members
hide Contact empty members
hide Auditorium empty members


list <|-left- OrganizationLevel
list <|-- Group

OrganizationLevel <|-- University
OrganizationLevel <|-- HR
OrganizationLevel <|-- Faculty
OrganizationLevel <|-- Department
OrganizationLevel o-left- Contact

University o-right- Faculty
University o-up- HR

Faculty o-right- Department

Department o-up- Group
Department o-- Auditorium

@enduml
