@startuml

!theme monokai_npp from ..\..\.styles
scale 2

frame nl1 as "  слой 1   " {
    circle nl1_1 as "нейрон 1"
    circle nl1_2 as "нейрон 2"
}
' frame nl2 as "  слой 2   " {
   ' circle nl2_1 as "нейрон 1"
   ' circle nl2_2 as "нейрон 2"
   ' circle nl2_3 as "нейрон 3"
' }

circle n1 as "отдельный нейрон 1"
circle n2 as "отдельный нейрон 2"

n1 ..> n2
nl1_1 ..> n1
nl1_2 ..> n1

' nl1_1 --> nl2_1
' nl1_1 --> nl2_2
' nl1_1 --> nl2_3

' nl1_2 --> nl2_1
' nl1_2 --> nl2_2
' nl1_2 --> nl2_3

@enduml
